print("Hello Word!")
var_nome = "rony"
print ("variavel ",var_nome)
lista = ["rony","pedro","giovanna","claudete"]
print (lista[2])
print ((var_nome+"\n")*5)
# pergunta = input("Digite alguma coisa: ")
# print (pergunta)
valorString = "1000"
valorint = int(valorString)
valorFloat = float(valorString)
print(valorFloat)
nome=input("Digite seu nome: ")
print("string convetida para primeira em maiuscula: ",nome.capitalize())
print("centralizando",nome.center(50))
print("conta caracteres: ",nome.count("n"))
print("retorna se é verdadeiro terminado com uma sequencia de caracteres: ",nome.endswith("ro"))
print("retorna a posição de string: ",nome.find("n"))
print("retorna se é alphanumerico ",nome.isalpha())
print("retorna se é alphanumerico ",nome.isnumeric())
print("retorna se é alphanumerico ",nome.isdigit())
print("lower: ",nome.lower())
print("upper: ",nome.upper())
print("islower: ",nome.islower())
print("isupper: ",nome.isupper())
print("isspace veirifica se é vazio: ",nome.isspace())
print("istitle: ",nome.istitle())
print("title primeira em maiuscula: ",nome.title())